USE foundation_system;

INSERT INTO roles (id, name, description, created_at, updated_at) VALUES
  (1, '系統管理員', '可管理全系統功能與設定', NOW(), NOW()),
  (2, '主管', '可檢視管理資料並執行審核', NOW(), NOW()),
  (3, '行政人員', '可維護日常業務資料', NOW(), NOW()),
  (4, '一般檢視者', '僅可檢視授權資料', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  description = VALUES(description),
  updated_at = NOW();

INSERT INTO permissions (code, name, module, created_at, updated_at) VALUES
  ('dashboard.view', '檢視總儀表板', 'dashboard', NOW(), NOW()),
  ('users.view', '檢視使用者', 'users', NOW(), NOW()),
  ('users.create', '新增使用者', 'users', NOW(), NOW()),
  ('users.update', '編輯使用者', 'users', NOW(), NOW()),
  ('roles.view', '檢視角色權限', 'roles', NOW(), NOW()),
  ('roles.manage', '管理角色權限', 'roles', NOW(), NOW()),
  ('donors.view', '檢視捐款人', 'donors', NOW(), NOW()),
  ('donors.manage', '管理捐款人', 'donors', NOW(), NOW()),
  ('donations.view', '檢視捐款紀錄', 'donations', NOW(), NOW()),
  ('donations.manage', '管理捐款紀錄', 'donations', NOW(), NOW()),
  ('activities.view', '檢視活動管理', 'activities', NOW(), NOW()),
  ('activities.manage', '管理活動管理', 'activities', NOW(), NOW()),
  ('volunteers.view', '檢視志工', 'volunteers', NOW(), NOW()),
  ('volunteers.manage', '管理志工', 'volunteers', NOW(), NOW()),
  ('documents.view', '檢視文件', 'documents', NOW(), NOW()),
  ('documents.manage', '管理文件', 'documents', NOW(), NOW()),
  ('reports.view', '檢視報表', 'reports', NOW(), NOW()),
  ('reports.export', '匯出報表', 'reports', NOW(), NOW()),
  ('settings.manage', '管理系統設定', 'settings', NOW(), NOW()),
  ('system_updates.manage', '管理系統更新', 'system_updates', NOW(), NOW()),
  ('annual_budgets.view', '檢視年度預算', 'annual_budgets', NOW(), NOW()),
  ('annual_budgets.manage', '管理年度預算', 'annual_budgets', NOW(), NOW()),
  ('annual_budgets.approve', '核定年度預算', 'annual_budgets', NOW(), NOW()),
  ('work_plans.view', '檢視工作計畫', 'work_plans', NOW(), NOW()),
  ('work_plans.manage', '管理工作計畫', 'work_plans', NOW(), NOW()),
  ('personnel.view', '檢視人事管理', 'personnel', NOW(), NOW()),
  ('personnel.manage', '管理人事管理', 'personnel', NOW(), NOW()),
  ('projects.view', '檢視專案管理', 'projects', NOW(), NOW()),
  ('projects.manage', '管理專案管理', 'projects', NOW(), NOW()),
  ('lecturers.view', '檢視講師管理', 'lecturers', NOW(), NOW()),
  ('lecturers.manage', '管理講師管理', 'lecturers', NOW(), NOW()),
  ('calendar.view', '檢視行事曆管理', 'calendar', NOW(), NOW()),
  ('calendar.manage', '管理行事曆管理', 'calendar', NOW(), NOW()),
  ('accounting.view', '檢視會計系統', 'accounting', NOW(), NOW()),
  ('accounting.manage', '管理會計系統', 'accounting', NOW(), NOW()),
  ('bank_accounts.view', '檢視銀行帳戶', 'bank_accounts', NOW(), NOW()),
  ('bank_accounts.manage', '管理銀行帳戶', 'bank_accounts', NOW(), NOW()),
  ('petty_cash.view', '檢視零用金', 'petty_cash', NOW(), NOW()),
  ('petty_cash.manage', '管理零用金', 'petty_cash', NOW(), NOW()),
  ('purchase_requests.view', '檢視採購申請', 'purchase_requests', NOW(), NOW()),
  ('purchase_requests.manage', '管理採購申請', 'purchase_requests', NOW(), NOW()),
  ('purchase_requests.approve', '核准採購申請', 'purchase_requests', NOW(), NOW()),
  ('income_expenses.view', '檢視收支紀錄', 'income_expenses', NOW(), NOW()),
  ('income_expenses.manage', '管理收支紀錄', 'income_expenses', NOW(), NOW()),
  ('payment_receipts.view', '檢視領款收據', 'payment_receipts', NOW(), NOW()),
  ('payment_receipts.manage', '管理領款收據', 'payment_receipts', NOW(), NOW()),
  ('lecturer_expenses.view', '檢視講師支出費用', 'lecturer_expenses', NOW(), NOW()),
  ('lecturer_expenses.manage', '管理講師支出費用', 'lecturer_expenses', NOW(), NOW()),
  ('travel_expenses.view', '檢視出差費用', 'travel_expenses', NOW(), NOW()),
  ('travel_expenses.manage', '管理出差費用', 'travel_expenses', NOW(), NOW()),
  ('payroll.view', '檢視薪資管理', 'payroll', NOW(), NOW()),
  ('payroll.manage', '管理薪資管理', 'payroll', NOW(), NOW()),
  ('leave_requests.view', '檢視人事請假', 'leave_requests', NOW(), NOW()),
  ('leave_requests.manage', '管理人事請假', 'leave_requests', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  module = VALUES(module),
  updated_at = NOW();

INSERT IGNORE INTO role_permissions (role_id, permission_id)
SELECT 1, id FROM permissions;

INSERT IGNORE INTO role_permissions (role_id, permission_id)
SELECT 2, id FROM permissions
WHERE code IN (
  'dashboard.view',
  'users.view',
  'roles.view',
  'donors.view',
  'donations.view',
  'activities.view',
  'volunteers.view',
  'documents.view',
  'reports.view',
  'reports.export',
  'annual_budgets.view',
  'annual_budgets.approve',
  'work_plans.view',
  'personnel.view',
  'projects.view',
  'lecturers.view',
  'calendar.view',
  'accounting.view',
  'bank_accounts.view',
  'petty_cash.view',
  'purchase_requests.view',
  'purchase_requests.approve',
  'income_expenses.view',
  'payment_receipts.view',
  'lecturer_expenses.view',
  'travel_expenses.view',
  'payroll.view',
  'leave_requests.view'
);

INSERT IGNORE INTO role_permissions (role_id, permission_id)
SELECT 3, id FROM permissions
WHERE code IN (
  'dashboard.view',
  'donors.view',
  'donors.manage',
  'donations.view',
  'donations.manage',
  'activities.view',
  'activities.manage',
  'volunteers.view',
  'volunteers.manage',
  'documents.view',
  'documents.manage',
  'annual_budgets.view',
  'annual_budgets.manage',
  'work_plans.view',
  'work_plans.manage',
  'projects.view',
  'projects.manage',
  'lecturers.view',
  'lecturers.manage',
  'calendar.view',
  'calendar.manage',
  'accounting.view',
  'accounting.manage',
  'bank_accounts.view',
  'bank_accounts.manage',
  'petty_cash.view',
  'petty_cash.manage',
  'purchase_requests.view',
  'purchase_requests.manage',
  'income_expenses.view',
  'income_expenses.manage',
  'payment_receipts.view',
  'payment_receipts.manage',
  'lecturer_expenses.view',
  'lecturer_expenses.manage',
  'travel_expenses.view',
  'travel_expenses.manage',
  'leave_requests.view',
  'leave_requests.manage'
);

INSERT IGNORE INTO role_permissions (role_id, permission_id)
SELECT 4, id FROM permissions
WHERE code IN (
  'dashboard.view',
  'donors.view',
  'donations.view',
  'activities.view',
  'volunteers.view',
  'documents.view',
  'reports.view',
  'annual_budgets.view',
  'work_plans.view',
  'projects.view',
  'lecturers.view',
  'calendar.view',
  'purchase_requests.view',
  'income_expenses.view',
  'payment_receipts.view',
  'leave_requests.view'
);
